services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/projet_python_user
    depends_on:
      - db

  bank_service:
    build:
      context: ./bank_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/projet_python_bank
    depends_on:
      - db

  accounts_service:
    build:
      context: ./accounts_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/projet_python_accounts
      - USER_SERVICE_URL=http://user_service:8001
      - BANK_SERVICE_URL=http://bank_service:8002
    depends_on:
      - db
      - user_service
      - bank_service

  db:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
