apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: finether
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/var/lib/postgresql/data"
