apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: finether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: badryb/finether-bank-service:v3
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:1234@bank-db-service:5432/projet_python_bank
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: finether
spec:
  selector:
    app: bank-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
