apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: finether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: badryb/finether-notification-service
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:1234@notification-db-service:5432/projet_python_notifications
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: finether
spec:
  selector:
    app: notification-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
