apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: finether
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /run/desktop/mnt/host/c/data/postgres
