apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: finether
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
  # Core API group - for basic resource metrics
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - configmaps
      - secrets
      - namespaces
      - persistentvolumeclaims
      - resourcequotas # For resource requests/limits
      - limitranges # For QoS class determination
      - events # For pod status reasons
    verbs: ["list", "watch"]

  # Apps API group - for workload metrics
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["list", "watch"]

  # Scheduling API group - for QoS and pod scheduling
  - apiGroups: ["scheduling.k8s.io"]
    resources:
      - priorityclasses # For QoS class metrics
    verbs: ["list", "watch"]

  # Node metrics - for node conditions and status
  - apiGroups: ["node.k8s.io"]
    resources:
      - runtimeclasses
    verbs: ["list", "watch"]

  # Storage API group - for PVC metrics
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["list", "watch"]

  # Required for auth
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: finether
