# accounts-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: finether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts-service
          image: badryb/finether-accounts-service:v3
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:1234@accounts-db-service:5432/projet_python_accounts
            - name: USER_SERVICE_URL
              value: http://user-service:8001
            - name: BANK_SERVICE_URL
              value: http://bank-service:8002
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: finether
spec:
  selector:
    app: accounts-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
